nav:
  - Home: 'index.md'
  - Claims:
    - Managing Claims: 'claims/claim_management.md'
    - Permission in Claims: 'claims/claim_permissions.md'
  - Permissions:
    - Adding New Permissions: 'permissions/adding_permissions.md'
  - Groups:
    - Group Management: 'groups/group_management.md'
    - Permission in Groups: 'groups/group_permissions.md'
    - Claims in Groups: 'groups/group_claims.md'
  - Events:
    - Claim Events: 'events/claim_events.md'
    - Group Events: 'events/group_events.md'
  - Admins:
    - Checking Admins: 'admins/admins.md'
  - User Configs:
    - About User Configs: 'userconfigs/index.md'
  - Subclaims:
    - Managing Subclaims: 'subclaims/subclaim_management.md'
    - Permission in Subclaims: 'subclaims/subclaim_permissions.md'

site_name: ClaimIt API
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - java